### PR TITLE
Update laravel-dompdf

### PR DESCRIPTION
**Pull request by PWParsons**
Update "laravel-dompdf" to 0.9.0 which adds support for DomPDF v1 / PHP8

### CODE REVIEW

**Comment by mc0de** [comment]
@PWParsons hi, could you do PR on fresh branch of develop? because this one has a lot of no longer relevant commits

**Comment by PWParsons** [comment]
Hi @mc0de, please excuse my ignorance. I'm new to contributing. How do I PR on fresh develop branch? To update the dependency yourself is most probably easier than answering my question but I will really appreciate your guidance.

I followed the instructions at https://jarv.is/notes/how-to-pull-request-fork-github/. What am I going wrong?

**Comment by mc0de** [comment]
@PWParsons it is updated now, use v2.0.6

**Comment by PWParsons** [comment]
Thank you @mc0de

**Pull request closed without merging**
