### PR TITLE
Manage lang path for Laravel >= 9

### PR DESCRIPTION
**Pull request by s-damian**
InvoiceServiceProvider: Manage lang path for Laravel >= 9

### CODE REVIEW

**Comment by mc0de** [comment]
hi, does this fix any particular issue?

**Comment by s-damian** [comment]
It doesn't fix a bug. But this is to make it consistent with Laravel's lang architecture >= 9

**Comment by mc0de** [comment]
this will be reviewed with next release if doesn't have any side effects

**Comment by nathan-io** [comment]
@mc0de this PR is definitely needed. 

When I installed this package in a L9 project and published its assets, all of our lang references broke. Some views even start throwing array to string exceptions. 

When I removed the `resources/lang` folder, the issue was resolved.

I also submitted a PR for this, as I didn't see this one.

**Comment by Jacobtims** [comment]
This is a serious problem...

**Comment by mc0de** [comment]
Thank you for PR

**Pull request merged**
